from pathlib import Path
from typing import Optional, Union

class CastleError(Exception):
    """Raised on invalid input while minting a token or loading a catalog."""

class Fingerprint:
    """An opaque browser-identity handle."""

    @staticmethod
    def chrome_148_macos() -> "Fingerprint": ...
    @property
    def user_agent(self) -> str: ...
    @property
    def ua_platform(self) -> str: ...
    @property
    def webgl_renderer(self) -> str: ...
    @property
    def locale(self) -> str: ...
    @property
    def time_zone(self) -> str: ...

class LocaleProfile:
    """A coherent geo/locale bundle."""

    @staticmethod
    def preset(tag: str) -> "LocaleProfile": ...
    @staticmethod
    def new(
        locale: str,
        time_zone: str,
        timezone_offset: int,
        summertime_offset: int,
        languages: list[str],
    ) -> "LocaleProfile": ...
    @staticmethod
    def en_us() -> "LocaleProfile": ...
    @staticmethod
    def en_gb() -> "LocaleProfile": ...
    @staticmethod
    def de_de() -> "LocaleProfile": ...
    @staticmethod
    def fr_fr() -> "LocaleProfile": ...
    @staticmethod
    def it_it() -> "LocaleProfile": ...
    @staticmethod
    def es_es() -> "LocaleProfile": ...
    @staticmethod
    def ja_jp() -> "LocaleProfile": ...
    @property
    def time_zone(self) -> str: ...
    @property
    def timezone_offset(self) -> int: ...
    @property
    def summertime_offset(self) -> int: ...
    @property
    def locale(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def languages(self) -> list[str]: ...
    @property
    def voice_language(self) -> str: ...
    @property
    def locale_date_string(self) -> str: ...

def mint_token(
    cuid: str,
    pk: str,
    ig: int,
    hostname: str,
    *,
    fingerprint: Optional[Fingerprint] = None,
    locale_profile: Optional[LocaleProfile] = None,
    jitter: bool = False,
    init_time_ms: Optional[int] = None,
    now_ms: Optional[int] = None,
) -> str: ...
def load_devices(path: Union[str, Path]) -> list[Fingerprint]: ...
def random_bundled_device() -> Fingerprint: ...
