/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * An opaque browser-identity handle. Obtain one from
 * `Fingerprint.chrome148Macos()`, `loadDevices`, or `randomBundledDevice`.
 */
export declare class Fingerprint {
  /** The bundled Chrome 148 / macOS profile. */
  static chrome148Macos(): Fingerprint
  get userAgent(): string
  get uaPlatform(): string
  get webglRenderer(): string
  get locale(): string
  get timeZone(): string
}

/**
 * A coherent geo/locale bundle. Use a preset (`LocaleProfile.deDe()` or
 * `LocaleProfile.preset("de-DE")`) or build one with `LocaleProfile.create(...)`.
 */
export declare class LocaleProfile {
  /**
   * Look up a bundled preset by locale tag (e.g. `"de-DE"`). Throws if there
   * is no preset for it.
   */
  static preset(tag: string): LocaleProfile
  /**
   * Build a profile, deriving `localeDateString` from `locale`. Throws when
   * the locale's date format is not built in.
   */
  static create(locale: string, timeZone: string, timezoneOffset: number, summertimeOffset: number, languages: Array<string>): LocaleProfile
  static enUs(): LocaleProfile
  static enGb(): LocaleProfile
  static deDe(): LocaleProfile
  static frFr(): LocaleProfile
  static itIt(): LocaleProfile
  static esEs(): LocaleProfile
  static jaJp(): LocaleProfile
  get timeZone(): string
  get timezoneOffset(): number
  get summertimeOffset(): number
  get locale(): string
  get language(): string
  get languages(): Array<string>
  get voiceLanguage(): string
  get localeDateString(): string
}

/** Load a custom device catalog (a JSON array of fingerprints) from `path`. */
export declare function loadDevices(path: string): Array<Fingerprint>

/**
 * Mint an `X-Castle-Request-Token`.
 *
 * `cuid`/`pk`/`ig`/`hostname` are required. `fingerprint` defaults to the
 * bundled Chrome 148 macOS profile. `localeProfile` overrides the geo/locale
 * fields; `jitter=true` varies the per-session timing/behavioral signals.
 * Throws on invalid input.
 */
export declare function mintToken(cuid: string, pk: string, ig: number, hostname: string, fingerprint?: Fingerprint | undefined | null, localeProfile?: LocaleProfile | undefined | null, jitter?: boolean | undefined | null, initTimeMs?: number | undefined | null, nowMs?: number | undefined | null): string

/** A uniformly random fingerprint from the bundled catalog. */
export declare function randomBundledDevice(): Fingerprint
